#!/usr/bin/python3
"""Logging module for autogenerated pentest reports"""

from datetime import datetime

GREEN = "\033[0;32m"
YELLOW = "\033[33m"
RED = "\033[1;31m"
RESET = "\033[0;0m"
BOLD = "\033[;1m"


def LOG(msg="Nothing to write", FD=None, crit="log"):
    """Functions to log with different criticality levels
    msg : str , the message to log
    FD : FileDescriptorOrPath, path to log file
    crit : str, criticlity level
    """
    if FD:
        match (crit):
            case "inf":
                FD.write(f"{GREEN}[i] INF [{str(datetime.now())}] : {msg}\n")
            case "log":
                FD.write(f"[~] LOG [{str(datetime.now())}] : {msg}\n")
            case "crit":
                FD.write(f"{YELLOW}[!] CRT [{str(datetime.now())}] : {msg}\n")
            case "err":
                FD.write(f"{RED}[X] ERR [{str(datetime.now())}] : {msg}\n")
    else:
        print("Error 100 : Log file close, cannot log.")
        exit(-100)
    FD.write(f"{RESET}")

