#!/usr/bin/python3
"""Logging module for autogenerated pentest reports"""

from datetime import datetime


def LOG(msg="Nothing to write", FD=None, crit="log"):
    """Functions to log with different criticality levels
    msg : str , the message to log
    FD : FileDescriptorOrPath, path to log file
    crit : str, criticlity level
    """
    if FD:
        match (crit):
            case "inf":
                FD.write("[i] INF [" + str(datetime.now()) + "] : " + msg + "\n")
            case "log":
                FD.write("[~] LOG [" + str(datetime.now()) + "] : " + msg + "\n")
            case "crit":
                FD.write("[!] CRT [" + str(datetime.now()) + "] : " + msg + "\n")
            case "err":
                FD.write("[X] ERR [" + str(datetime.now()) + "] : " + msg + "\n")
    else:
        print("Error 100 : Log file close, cannot log.")
        exit(-100)

